version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cookbook
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: cookbook-api
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: ./dockerfile
    ports:
      - 5000:5001

  ui:
    image: front-end
    depends_on:
      - api
    build:
      context: front-end
      dockerfile: ./dockerfile
    ports:
      - 3000:3001

volumes:
  mongo_volume:
